# This is a template yaml for the aptos-indexer-processor.
health_check_port: 8085
server_config:
  processor_config:
    type: "events_processor"
  backfill_config:
    backfill_alias: "events_processor_backfill_1"
  transaction_stream_config:
    indexer_grpc_data_service_address: "https://grpc.testnet.aptoslabs.com:443"
    # starting_version: 0
    auth_token: "aptoslabs_TJs4NQU8Xf5_EJMNnZFPXRH6YNpWM7bCcurMBEUtZtRb6"
    request_name_header: "events-processor"
  db_config:
    postgres_connection_string: postgresql://seanyang:@localhost:5432/example
